# fly.toml app configuration file generated for pocket-react on 2024-10-29T20:34:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocket-react'
primary_region = 'arn'

[build]

[[mounts]]
  source = 'litefs'
  destination = '/var/lib/litefs'

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
