# fly.toml app configuration file generated for pocket-react on 2024-10-28T10:01:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocket-react'
primary_region = 'arn'

[mounts]
  source = "pb_data"
  destination = "/pb_data"

[env]
  SQLITE_PATH = "/pb_data/data.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
