# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main serve"  # Added 'serve' command
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "frontend/dist"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]

[misc]
  clean_on_exit = true

[log]
  time = false

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[screen]
  clear_on_rebuild = true
  